services:
  db:
    image: postgres:17-alpine
    container_name: stomatology-postgres
    environment:
        - POSTGRES_USER=localhost
        - POSTGRES_PASSWORD=localhost
        - POSTGRES_DB=stomatology
    ports:
      - "5455:5432"
    volumes:
      - ./postgres:/var/lib/postgresql/data
